const EuropeCountries = [
  {
    country: 'Albania',
    capital: 'Tirana',
    latitude: 41.3275,
    longitude: 19.8187,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/al/vector.svg',
  },
  {
    country: 'Andorra',
    capital: 'Andorra la Vella',
    latitude: 42.5063,
    longitude: 1.5218,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ad/vector.svg',
  },
  {
    country: 'Austria',
    capital: 'Vienna',
    latitude: 48.2082,
    longitude: 16.3738,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/at/vector.svg',
  },
  {
    country: 'Belarus',
    capital: 'Minsk',
    latitude: 53.9045,
    longitude: 27.5615,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/by/vector.svg',
  },
  {
    country: 'Belgium',
    capital: 'Brussels',
    latitude: 50.8503,
    longitude: 4.3517,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/be/vector.svg',
  },
  {
    country: 'Bosnia and Herzegovina',
    capital: 'Sarajevo',
    latitude: 43.8564,
    longitude: 18.4131,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ba/vector.svg',
  },
  {
    country: 'Bulgaria',
    capital: 'Sofia',
    latitude: 42.6977,
    longitude: 23.3219,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/bg/vector.svg',
  },
  {
    country: 'Croatia',
    capital: 'Zagreb',
    latitude: 45.815,
    longitude: 15.9819,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/hr/vector.svg',
  },
  {
    country: 'Cyprus',
    capital: 'Nicosia',
    latitude: 35.1856,
    longitude: 33.3823,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/cy/vector.svg',
  },
  {
    country: 'Czech Republic',
    capital: 'Prague',
    latitude: 50.0755,
    longitude: 14.4378,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/cz/vector.svg',
  },
  {
    country: 'Denmark',
    capital: 'Copenhagen',
    latitude: 55.6761,
    longitude: 12.5683,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/dk/vector.svg',
  },
  {
    country: 'Estonia',
    capital: 'Tallinn',
    latitude: 59.437,
    longitude: 24.7536,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ee/vector.svg',
  },
  {
    country: 'Finland',
    capital: 'Helsinki',
    latitude: 60.1699,
    longitude: 24.9384,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/fi/vector.svg',
  },
  {
    country: 'France',
    capital: 'Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/fr/vector.svg',
  },
  {
    country: 'Germany',
    capital: 'Berlin',
    latitude: 52.52,
    longitude: 13.405,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/de/vector.svg',
  },
  {
    country: 'Greece',
    capital: 'Athens',
    latitude: 37.9838,
    longitude: 23.7275,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/gr/vector.svg',
  },
  {
    country: 'Hungary',
    capital: 'Budapest',
    latitude: 47.4979,
    longitude: 19.0402,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/hu/vector.svg',
  },
  {
    country: 'Iceland',
    capital: 'Reykjavik',
    latitude: 64.1466,
    longitude: -21.9426,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/is/vector.svg',
  },
  {
    country: 'Ireland',
    capital: 'Dublin',
    latitude: 53.3498,
    longitude: -6.2603,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ie/vector.svg',
  },
  {
    country: 'Italy',
    capital: 'Rome',
    latitude: 41.9028,
    longitude: 12.4964,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/it/vector.svg',
  },
  {
    country: 'Kosovo',
    capital: 'Pristina',
    latitude: 42.6629,
    longitude: 21.1655,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/xk/vector.svg',
  },
  {
    country: 'Latvia',
    capital: 'Riga',
    latitude: 56.9496,
    longitude: 24.1052,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/lv/vector.svg',
  },
  {
    country: 'Liechtenstein',
    capital: 'Vaduz',
    latitude: 47.141,
    longitude: 9.5215,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/li/vector.svg',
  },
  {
    country: 'Lithuania',
    capital: 'Vilnius',
    latitude: 54.6872,
    longitude: 25.2797,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/lt/vector.svg',
  },
  {
    country: 'Luxembourg',
    capital: 'Luxembourg City',
    latitude: 49.6116,
    longitude: 6.1319,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/lu/vector.svg',
  },
  {
    country: 'Russia',
    capital: 'Moscow',
    latitude: 55.7558,
    longitude: 37.6173,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ru/vector.svg',
  },
  {
    country: 'San Marino',
    capital: 'San Marino',
    latitude: 43.9424,
    longitude: 12.4578,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/sm/vector.svg',
  },
  {
    country: 'Serbia',
    capital: 'Belgrade',
    latitude: 44.7866,
    longitude: 20.4489,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/rs/vector.svg',
  },
  {
    country: 'Slovakia',
    capital: 'Bratislava',
    latitude: 48.1486,
    longitude: 17.1077,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/sk/vector.svg',
  },
  {
    country: 'Slovenia',
    capital: 'Ljubljana',
    latitude: 46.0569,
    longitude: 14.5058,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/si/vector.svg',
  },
  {
    country: 'Spain',
    capital: 'Madrid',
    latitude: 40.4168,
    longitude: -3.7038,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/es/vector.svg',
  },
  {
    country: 'Sweden',
    capital: 'Stockholm',
    latitude: 59.3293,
    longitude: 18.0686,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/se/vector.svg',
  },
  {
    country: 'Switzerland',
    capital: 'Bern',
    latitude: 46.9479,
    longitude: 7.4474,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ch/vector.svg',
  },
  {
    country: 'Ukraine',
    capital: 'Kyiv',
    latitude: 50.4501,
    longitude: 30.5234,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ua/vector.svg',
  },
  {
    country: 'United Kingdom',
    capital: 'London',
    latitude: 51.5074,
    longitude: -0.1278,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/gb/vector.svg',
  },
  {
    country: 'Malta',
    capital: 'Valletta',
    latitude: 35.8989,
    longitude: 14.5146,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/mt/vector.svg',
  },
  {
    country: 'Moldova',
    capital: 'Chisinau',
    latitude: 47.0105,
    longitude: 28.8638,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/md/vector.svg',
  },
  {
    country: 'Monaco',
    capital: 'Monaco',
    latitude: 43.7384,
    longitude: 7.4246,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/mc/vector.svg',
  },
  {
    country: 'Montenegro',
    capital: 'Podgorica',
    latitude: 42.4304,
    longitude: 19.2594,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/me/vector.svg',
  },
  {
    country: 'Netherlands',
    capital: 'Amsterdam',
    latitude: 52.3702,
    longitude: 4.8952,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/nl/vector.svg',
  },
  {
    country: 'North Macedonia',
    capital: 'Skopje',
    latitude: 41.9973,
    longitude: 21.4279,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/mk/vector.svg',
  },
  {
    country: 'Norway',
    capital: 'Oslo',
    latitude: 59.9139,
    longitude: 10.7522,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/no/vector.svg',
  },
  {
    country: 'Poland',
    capital: 'Warsaw',
    latitude: 52.2297,
    longitude: 21.0122,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/pl/vector.svg',
  },
  {
    country: 'Portugal',
    capital: 'Lisbon',
    latitude: 38.7223,
    longitude: -9.1393,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/pt/vector.svg',
  },
  {
    country: 'Romania',
    capital: 'Bucharest',
    latitude: 44.4396,
    longitude: 26.0963,
    image: 'https://raw.githubusercontent.com/Ginohmk/worldMaps/main/maps/ro/vector.svg',
  },

];
export default EuropeCountries;
